name: Rust test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - '**/Cargo.toml'
      - 'Cargo.lock'
      - '**/Cargo.lock'

jobs:
  build:
    uses: chalharu/workflows/.github/workflows/rust-ci.yaml@b38333d680878a2156ff25b255cf7174c9a3a065 # main
