name: Rust test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - '**/Cargo.toml'
      - 'Cargo.lock'
      - '**/Cargo.lock'

jobs:
  build:
    uses: chalharu/workflows/.github/workflows/rust-ci.yaml@main
